Maintain aspect ratio of image stimuli
CAMBI-tech/BciPy pull request #11
Opened 2018-07-09 20:18 UTC by smektala

2018-07-10 14:45 UTC, tab-cmd requested changes
Hey, this looks good. I added some comments, please address then let's have Betts test it when you're feeling better and back in the office

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/mode/RSVPKeyboard.py
> +            ignore_file = open('bcipy/gui/ignore.txt', 'r')
For now, let's not add an ignore feature.

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/mode/RSVPKeyboard.py
> +        parameters = load_json_parameters('bcipy/parameters/parameters.json', value_cast=True)
Let's make this location a static variable on line 11 called `PARAMETER_LOCATION = 'bcipy/parameters/parameters.json'`, then here call self.PARAMETER_LOCATION. That will help us if other parameters are wanted.

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/mode/RSVPKeyboard.py
> +        if(os.path.isdir(data_save_loc)):
This is a good check. Looking at the parameters.json it is not an absolute path. The correct syntax would be `if os.path.isdir(data_save_loc)`, if it's not found raise an error message.

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/params_form.py
> +                    is_directory = param.type == "directorypath"
make is `is_directory` false by default and check with an if statement

2018-07-10 14:45 UTC, sci-tab commented on bcipy/display/rsvp/rsvp_disp.py
> +from PIL import Image
We should still add to requirements.txt if not already

2018-07-10 14:45 UTC, sci-tab commented on bcipy/display/rsvp/rsvp_disp.py
> +                    self.sti.size = (self.height_stim, (image_height/image_width) * self.height_stim)
syntax error. should be `(self.height_stim, (image_height / image_width) * self.height_stim)`

2018-07-10 14:45 UTC, sci-tab commented on bcipy/display/rsvp/rsvp_disp.py
> +                    self.sti.size = ((image_width/image_height) * self.height_stim, self.height_stim)
same here

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/gui_main.py
> +        if action == 'default' and isinstance(btn, wx.ComboBox):
This should come first, then the other if statement button (to avoid binding 2x). add some comments here

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/gui_main.py
> +        print('dropped items in box')
maybe the message could be `dropdown selected`

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/params_form.py
> +                    new_path = new_path + "\\"
Will this be true for mac and windows?

2018-07-10 14:45 UTC, sci-tab commented on bcipy/helpers/load.py
> +        elif actual_type == 'str' or actual_type == 'filepath' or actual_type == 'directorypath':
or `'path' in actual_type`

2018-07-10 14:45 UTC, sci-tab commented on bcipy/gui/params_form.py
> +                p = self.params[key]
no single letter variables, name it

2018-07-10 14:46 UTC, sci-tab commented
Also, add some in-line comments to the added functions!

2018-07-11 00:52 UTC, tab-cmd approved these changes
One more small change and then please merge it!

2018-07-11 00:52 UTC, sci-tab commented on bcipy/gui/params_form.py
> +                p = self.params[key]
no single letter variables! name it

2018-07-11 00:52 UTC, sci-tab commented on bcipy/helpers/stimuli_generation.py
> +            sample = ['bcipy/static/images/bci_main_images/PLUS.png']
thanks for fixing

2018-07-11 00:59 UTC, merged