Multi-modal acquisition
CAMBI-tech/BciPy pull request #171
Opened 2021-09-08 23:53 UTC by lawhead

# Overview

Re-architected the data acquisition module in support of multi-modal acquisition.

## Ticket

https://www.pivotaltracker.com/story/show/178699590
https://www.pivotaltracker.com/story/show/178875719

## Contributions

- Created a new lightweight data acquisition client for reading from LSL data sources. Multiple clients can be created to read from different sources (ex. EEG and eye tracker).
- Separated out the responsibilities for recording and querying data.
- Deprecated MarkerWriter
- Deprecated support for TCP connections.
- Renamed `supported_device` to `preconfigured_device`.
- Added a Clock abstraction, which by default uses the pylsl local_clock.
- Refactored data queries to use timestamps rather than sample number.
- Added code to demonstrate functionality and usage.

## Test

- Run all unit tests
- Run Calibration task -> offline_analysis -> Copy Phrase task.
- Confirm timing data.

2021-09-09 18:02 UTC, sci-tab requested changes
This is a nice change! I added some comments. Running locally, I see the TRG column is still present but has sensor values when it was 0.0 before? I see that TRG_device_stream used to have those values. Is this due to how we mock channels for serving?

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/datastream/lsl_server.py
> +            # TODO: different types of metadata depending on the content type
Let's make a ticket for this! I don't know how much we use the metadata, but it seems useful

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/demo/demo_eye_tracker_server.py
> +def eye_tracker_data_generator(display_x=1920, display_y=1080):
We should move this somewhere... datastream/generator?

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/demo/demo_eeg_with_switch.py
> +    eeg_device = DeviceSpec(name="LSL_demo",
rename?

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/demo/demo_lsl_server.py
> +def custom_generator(device_spec: DeviceSpec, low=-1000, high=1000):
move to wherever the other eye tracker generator was moved!

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/demo/demo_switch.py
> +    # @override
some cleanup on this file

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/demo/demo_switch.py
> +    # pyqt_gui()
unused

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/demo/demo_switch.py
> +class SwitchGui(BCIGui):
woah! This is awesome for testing

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/errors.py
> +class InvalidClockError(Exception):
Other modules use the name `exceptions.py`. It may be good to change for consistency, but errors is descriptive enough

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/protocols/lsl/lsl_recorder.py
> +        self.sleep_seconds = 0.2
Do you think these values might change? chunk size and sleep seconds?

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/protocols/lsl/lsl_recorder.py
> +        # TODO: do we need to use max_chunk_size here
pull out to a spike?

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/acquisition/protocols/lsl/lsl_recorder.py
> +# pylint: disable=import-outside-toplevel
This can be moved closer to the import

2021-09-09 18:02 UTC, tab-cmd commented on bcipy/helpers/clock.py
> +    default value is the LabStreamingLayer (LSL) local_clock.
We might indicate why it's the default...

2021-09-10 18:15 UTC, lawhead commented on bcipy/acquisition/datastream/lsl_server.py
> +            # TODO: different types of metadata depending on the content type
https://www.pivotaltracker.com/story/show/179542651

2021-09-10 20:20 UTC, lawhead commented on bcipy/acquisition/protocols/lsl/lsl_recorder.py
> +        # TODO: do we need to use max_chunk_size here
https://www.pivotaltracker.com/story/show/179544118

2021-09-10 20:24 UTC, lawhead commented on bcipy/acquisition/protocols/lsl/lsl_recorder.py
> +        self.sleep_seconds = 0.2
I created a ticket to explore this in more detail (see comment below). The `max_chunk_size` here is the default value that's used if you call `pull_chunk` without any parameters. The user can set this to a different value after the LslRecordingThread is instantiated (and before it starts recording). There is definitely a relationship between sleep seconds and max_chunk_size, though, and we may want to do some validation checks before setting.

2021-09-10 20:24 UTC, lawhead commented on bcipy/acquisition/protocols/lsl/lsl_recorder.py
> +# pylint: disable=import-outside-toplevel
Thanks, good catch. Weird that this was here.

2021-09-10 21:46 UTC, lawhead commented on bcipy/acquisition/demo/demo_lsl_server.py
> +def custom_generator(device_spec: DeviceSpec, low=-1000, high=1000):
Actually I think this one can be removed at this point.

2021-09-10 22:40 UTC, lawhead commented on bcipy/acquisition/demo/demo_eye_tracker_server.py
> +def eye_tracker_data_generator(display_x=1920, display_y=1080):
I added a new package for `acquisition/datastream/mock` and moved the `eye_tracker_server.py` and `switch.py` here.

2021-09-15 23:08 UTC, sci-tab approved these changes

2021-09-16 16:15 UTC, merged