added ssvep to cvep method
CAMBI-tech/BciPy pull request #232
Opened 2022-07-25 16:15 UTC by AidaFakhry

# Overview

A method that uses the refresh rate on the monitor and returns a code for SSVEP. every frame of / on for x seconds.

## Ticket 

[Ticket 2](https://www.pivotaltracker.com/n/projects/2460065/stories/182492679)

## Contributions

- Created method that uses the refresh rate on the monitor and returns a code for SSVEP. every frame of / on for x seconds.

## Test

- Unit tested.

## Documentation

Are documentation updates required? In-line, README, or [documentation](https://github.com/BciPy/bcipy.github.io)? Verify the updates you did here.

## Changelog

Is the CHANGELOG.md updated with your detailed changes? N/a

2022-08-01 22:23 UTC, lawhead requested changes
I don't understand what the returned list represents in the `ssvep_to_cvep` function and how the calling function would use the results. I would expect that for a given refresh_rate it would return the same number of items, but

    ssvep_to_cvep(refresh_rate=50, flicker_rate=10)
    => [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    ssvep_to_cvep(refresh_rate=50, flicker_rate=25)
    => [0, 0, 1, 1]

If the intent is to communicate a flash pattern, we need to know how much time each entry in the list represents, so the units are important to consider. For instance, if we are returning a pattern for 1 second display, the items in the list could each be 1hz worth of data (50 items for a 50hz refresh rate). Alternatively, this could be a tuple with the on/off duration in seconds . For the second example, this would be (0.5, 0.5) for half second off, followed by half second on.

@sci-tab, how would it be easiest to consume this data when writing displays?

2022-08-01 22:23 UTC, lawhead commented on bcipy/helpers/stimuli.py
> +def ssvep_to_cvep(refresh_rate: int = 60, flicker_rate: float = 10.0):
We need some documentation for this function to give a summary of what it's for (particularly if someone doesn't know what SSVEP and CVEP are abbreviations for), it's parameters (units?), etc.

Also, there should be a return type (`List[float]`), and the documentation should explain what this represents.

2022-08-01 22:23 UTC, lawhead commented on bcipy/helpers/stimuli.py
> +    # determine if lenth_flickerr is an integer using .is_integer()
There's a typo in the comment: `lenth_flickerr` -> `length_flicker`. But you can probably just remove this comment since it's redundant with the code.

2022-08-01 22:23 UTC, lawhead commented on bcipy/helpers/stimuli.py
> +        raise Exception("Provided flicker rate must divide into refresh rate.")
`length_flicker` is only used as a float to check the whether it's evenly divisible so we might want to immediately cast it as an int:

    if length_flicker.is_integer():
        length_flicker = int(length_flicker)
    else:
         raise Exception("Provided flicker rate must divide into refresh rate.")

2022-08-01 22:23 UTC, lawhead commented on bcipy/helpers/stimuli.py
> +    return test_array
Python has a couple of list methods that may be helpful here. The `+` operator can be used to concatenate lists (`[1,2] + [3,4]` => `[1,2,3,4]`), and the `*` operator is a shortcut for constructing a list of consecutive elements with the same value (`[0] * 3` => `[0,0,0]`).

Another observation is that we're basically just toggling between `0` (for even indices) and `1` (for odd indices).  We can determine if a number is even or odd by using the modulus operator `%`.

So with all that, one way to shorten the above code is something like:

    test_array = []
    for i in range(length_flicker):
        test_array += [i % 2] * length_flicker

2022-08-15 16:45 UTC, sci-tab commented
> I don't understand what the returned list represents in the `ssvep_to_cvep` function and how the calling function would use the results. I would expect that for a given refresh_rate it would return the same number of items, but
> 
> ```
> ssvep_to_cvep(refresh_rate=50, flicker_rate=10)
> => [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
> ssvep_to_cvep(refresh_rate=50, flicker_rate=25)
> => [0, 0, 1, 1]
> ```
> 
> If the intent is to communicate a flash pattern, we need to know how much time each entry in the list represents, so the units are important to consider. For instance, if we are returning a pattern for 1 second display, the items in the list could each be 1hz worth of data (50 items for a 50hz refresh rate). Alternatively, this could be a tuple with the on/off duration in seconds . For the second example, this would be (0.5, 0.5) for half second off, followed by half second on.
> 
> @sci-tab, how would it be easiest to consume this data when writing displays?

That is the intended output and how the VEP display would be able to use it. I'll pick it up from here and see if I can spot the issue!

2022-08-17 22:28 UTC, lawhead approved these changes

2022-08-19 16:28 UTC, merged