Matrix configuration
CAMBI-tech/BciPy pull request #289
Opened 2023-08-24 16:02 UTC by lawhead

# Overview

Added the ability to configure matrix displays with parameters for the number of rows and columns.

## Ticket

https://www.pivotaltracker.com/story/show/184419221

## Contributions

- Created a new module for computing matrix positions relative to a Layout.
- Updated the MatrixDisplay to use row and column parameters for computing positions.
- Added functionality to the layout module for resizing elements and for computing positions relative to other elements.
- Added parameters for matrix_rows, matrix_columns, and matrix_width_pct
- Updated calibration and copy phrase tasks to use the new parameters

## Test

- Created comprehensive unit tests for position calculations and ran them.
- Ran matrix demos using the new parameters.
- Ran calibration and copy phrase tasks, varying the number of rows and columns, to confirm that the configured changes were applied.

2023-08-24 20:19 UTC, sci-tab requested changes
Looks great! This does not include the option to change keyboard arrangements. I tested the below snippet locally, and it works well with your changes. We could put these in `helpers/symbols`, add a parameter on alphabet arrangement with three options, and toggle only in the matrix task for now (with a follow-up for RSVP)

```python
def qwerty_alphabet(parameters=None):
    """QWERTY Alphabet.

    Function used to return the QWERTY arrangement for symbols

    Returns
    -------
        array of letters.
    """
    if parameters and not parameters['is_txt_stim']:
        # construct an array of paths to images
        raise NotImplementedError('QWERTY alphabet not implemented for images')
    
    qwerty = 'qwertyuiopasdfghjklzxcvbnm'.upper()

    return list(qwerty) + [BACKSPACE_CHAR, SPACE_CHAR]

def most_frequent_alphabet(parameters=None):
    """Most frequent alphabet.

    Function used to standardize the symbols we use in the English alphabet.

    Returns
    -------
        array of letters.
    """
    if parameters and not parameters['is_txt_stim']:
        # construct an array of paths to images
        raise NotImplementedError('Most frequent alphabet not implemented for images')
    
    most_frequent = 'etaoinshrdlcumwfgypbvkjxqz'.upper()

    return list(most_frequent) + [BACKSPACE_CHAR, SPACE_CHAR]
```

2023-08-24 20:19 UTC, tab-cmd commented on bcipy/parameters/parameters.json
> +  "matrix_width_pct": {
this could be `matrix_width`. We describe the inputs in the description

2023-08-24 20:19 UTC, tab-cmd commented on bcipy/parameters/parameters.json
> +    "value": "UNIFORM",
👍🏼

2023-08-24 20:34 UTC, sci-tab commented
++ CHANGELOG

2023-08-24 21:02 UTC, lawhead commented
I did some exploration on the qwerty layout. The problem is that it's not a straight grid. There are 10 letters in the first row, 9 in the second, and 7 in the third (9 if you include backspace and space). Other keyboards I looked at compensate for this by putting in additional filler symbols (semi-colon, question-mark, etc), but doing so would change our alphabet.

We could potentially have a 10 x 3 grid and use blanks on the end of the shorter rows. Or we could have a different layout that can accommodate irregular rows. The second option would be more work to determine positioning, but the integration would be straightforward. Might be a good thing to discuss with the group.

2023-08-24 21:22 UTC, sci-tab commented
> I did some exploration on the qwerty layout. The problem is that it's not a straight grid. There are 10 letters in the first row, 9 in the second, and 7 in the third (9 if you include backspace and space). Other keyboards I looked at compensate for this by putting in additional filler symbols (semi-colon, question-mark, etc), but doing so would change our alphabet.
> 
> We could potentially have a 10 x 3 grid and use blanks on the end of the shorter rows. Or we could have a different layout that can accommodate irregular rows. The second option would be more work to determine positioning, but the integration would be straightforward. Might be a good thing to discuss with the group.

Given the shared reference resource:
![image](https://github.com/CAMBI-tech/BciPy/assets/11506578/6df60dd9-c089-4ef0-ba69-40360bb86c71)

We could do the 10 x 3 as you suggest, with a `backspace` at the end of the second to fill it and put the space in the center of the third. The rest would be empty in that case without issue. 

We may need to define a more enhanced `Keyboard` option in the long run with defined characters representing empty grid locations as things progress: 

Where the return could be,

```
qwerty_keyboard = [
    'qwertyuiop',
    'asdfghjkl<',
    '*zxcv_bnm*',
]
```

`*` or some other symbol indicating padding relative to other keyboard elements but not selectable. We should get some feedback, though there is some wiggle room with this. 
 
Probably not adding any selectable characters, though, as that would take some LM input to figure out (although it may just be stripping and replacing as we do with the space).

2023-08-25 00:43 UTC, sci-tab approved these changes

2023-08-25 02:42 UTC, sci-tab commented
I'll add an asana item to discuss this next week! We won't have a sprint demo the following as I'll be on PTO.

2023-08-25 22:56 UTC, lawhead commented
I pushed a small change to allow for QWERTY layouts using the discussed approach. After discussion with the group we can finalize the ordering.

2023-08-30 16:26 UTC, merged